import { spawn, execSync } from 'child_process';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import {
  getConfigDir
} from './config.js';

/**
 * Detect which docker compose command to use
 */
function getComposeCommand() {
  try {
    execSync('docker compose version', { stdio: 'pipe' });
    return { cmd: 'docker', args: ['compose'] };
  } catch (e) {
    try {
      execSync('docker-compose --version', { stdio: 'pipe' });
      return { cmd: 'docker-compose', args: [] };
    } catch (e2) {
      return { cmd: 'docker', args: ['compose'] };
    }
  }
}

/**
 * Generate a random secret for Docker services
 */
function generateSecret() {
  return crypto.randomBytes(16).toString('hex');
}

/**
 * Check if Docker is installed and running
 */
export async function checkDocker() {
  const installed = await new Promise((resolve) => {
    const check = spawn('docker', ['--version']);
    check.on('close', (code) => resolve(code === 0));
    check.on('error', () => resolve(false));
  });

  if (!installed) {
    return {
      installed: false,
      running: false,
      error: 'Docker not found. Please install Docker from https://docs.docker.com/engine/install/'
    };
  }

  const running = await new Promise((resolve) => {
    const check = spawn('docker', ['ps', '-q'], {
      stdio: ['pipe', 'pipe', 'pipe']
    });
    check.on('close', (code) => resolve(code === 0));
    check.on('error', () => resolve(false));
  });

  if (!running) {
    return {
      installed: true,
      running: false,
      error: 'Docker is installed but not running. Please start Docker Desktop.'
    };
  }

  return {
    installed: true,
    running: true
  };
}

/**
 * Generate docker-compose.yml from config
 * @param {object} config
 * @param {number} stackId - 1-based stack identifier (default 1)
 */
export function generateDockerCompose(config, stackId = 1) {
  if (!config.secrets) {
    config.secrets = {
      drachtio: 'cymru',
      freeswitch: 'cymru'
    };
  }

  // PORT CALCULATION
  const idOffset = stackId - 1;

  // SIP Ports (Default 5060 -> 5060, 5070, 5080)
  const baseSipPort = (config.sip && config.sip.port) ? config.sip.port : 5060;
  const sipPort = baseSipPort + (idOffset * 10);

  // FreeSWITCH SIP Port (Default 5080 -> 5080, 5090, 5100)
  const fsSipPort = 5080 + (idOffset * 10);

  // RTP Range (Default 30000-30100 -> 30200-30300)
  const rtpStart = 30000 + (idOffset * 200);
  const rtpEnd = rtpStart + 100;

  // Drachtio Admin Port (Default 9022 -> 9022, 9023, 9024)
  const drachtioAdminPort = 9022 + idOffset;

  const isPiMode = config.deployment && config.deployment.mode === 'pi-split';
  const drachtioImage = isPiMode ? 'drachtio/drachtio-server:0.9.4' : 'drachtio/drachtio-server:latest';
  const freeswitchImage = 'drachtio/drachtio-freeswitch-mrf:latest';
  const platformLine = isPiMode ? '\n    platform: linux/arm64' : '';

  const installationType = config.installationType || 'both';
  const services = [];

  // Voice services (drachtio, freeswitch, voice-app)
  if (installationType === 'voice-server' || installationType === 'both') {
    services.push(`  drachtio:
    image: ${drachtioImage}${platformLine}
    container_name: drachtio-${stackId}
    restart: unless-stopped
    network_mode: host
    command: >
      drachtio
      --contact "sip:*:${sipPort};transport=tcp,udp"
      --secret \${DRACHTIO_SECRET:-cymru}
      --port ${drachtioAdminPort}
      --loglevel info

  freeswitch:
    image: ${freeswitchImage}${platformLine}
    container_name: freeswitch-${stackId}
    restart: unless-stopped
    network_mode: host
    command: >
      freeswitch
      --sip-port ${fsSipPort}
      --rtp-range-start ${rtpStart}
      --rtp-range-end ${rtpEnd}
      --ext-rtp-ip \${EXTERNAL_IP:-127.0.0.1}
      --ext-sip-ip \${EXTERNAL_IP:-127.0.0.1}
      --advertise-external-ip
    volumes:
      - ${getConfigDir()}/recordings:/app/recordings
    environment:
      - EXTERNAL_IP=\${EXTERNAL_IP:-127.0.0.1}

  voice-app:
    build: ${config.paths.voiceApp}
    container_name: voice-app-${stackId}
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env${stackId === 1 ? '' : '-' + stackId}
    volumes:
      - ${config.paths.voiceApp}/audio:/app/audio
      - ${config.paths.voiceApp}/config:/app/config
      - ${getConfigDir()}/recordings:/app/recordings
    depends_on:
      - drachtio
      - freeswitch`);
  }

  // API & Mission Control
  // NOTE: These are now run as native host processes by the CLI (start.js)
  // We do NOT add them to Docker to avoid port conflicts (3030, 3333)
  if (installationType === 'api-server' || installationType === 'both') {
    // Intentionally empty - run on host
  }

  return `# CRITICAL: All containers must use network_mode: host
# Stack ID: ${stackId}
# SIP Port: ${sipPort}
# RTP Range: ${rtpStart}-${rtpEnd}
# Generated by gemini-phone CLI

services:
${services.join('\n\n')}
`;
}

/**
 * Generate .env file from config
 * @param {object} config
 * @param {number} stackId - Default 1
 */
export function generateEnvFile(config, stackId = 1) {
  if (!config.secrets) {
    config.secrets = {
      drachtio: generateSecret(),
      freeswitch: generateSecret()
    };
  }

  // PORT CALCULATION
  const idOffset = stackId - 1;

  const sipPort = 5060 + (idOffset * 10);
  const registrarPort = 5060; // Upstream PBX always listens on 5060 (usually)

  // Drachtio Admin
  const drachtioAdminPort = 9022 + idOffset;

  // FreeSWITCH
  const fsPort = 8021 + idOffset; // Event Socket

  // Voice App
  const httpPort = (config.server.httpPort || 3000) + (idOffset * 2);
  const wsPort = 3001 + (idOffset * 2);

  let geminiApiUrl;
  if (config.deployment && config.deployment.mode === 'pi-split' && config.deployment.pi && config.deployment.pi.macIp) {
    geminiApiUrl = `http://${config.deployment.pi.macIp}:${config.server.geminiApiPort}`;
  } else if (config.deployment && config.deployment.mode === 'voice-server' && config.deployment.apiServerIp) {
    geminiApiUrl = `http://${config.deployment.apiServerIp}:${config.server.geminiApiPort}`;
  } else {
    geminiApiUrl = `http://localhost:${config.server.geminiApiPort || 3333}`;
  }

  const lines = [
    '# ====================================',
    '# WARNING: DO NOT SHARE THIS FILE',
    '# Contains API keys and passwords',
    '# ====================================',
    `# Gemini Phone Configuration - Stack ${stackId}`,
    '# Generated by gemini-phone CLI',
    '# ====================================',
    '',
    '# Network Configuration',
    `EXTERNAL_IP=${config.server.externalIp === 'auto' ? 'auto' : config.server.externalIp}`,
    '',
    '# Drachtio Configuration',
    'DRACHTIO_HOST=127.0.0.1',
    `DRACHTIO_PORT=${drachtioAdminPort}`,
    `DRACHTIO_SECRET=${config.secrets.drachtio}`,
    `DRACHTIO_SIP_PORT=${sipPort}`,
    '',
    '# FreeSWITCH Configuration',
    'FREESWITCH_HOST=127.0.0.1',
    `FREESWITCH_PORT=${fsPort}`,
    'FREESWITCH_SECRET=JambonzR0ck$',
    '',
    '# FreePBX / SIP Configuration',
    `SIP_DOMAIN=${config.sip.domain}`,
    `SIP_REGISTRAR=${config.sip.registrar}`,
    `SIP_REGISTRAR_PORT=${registrarPort}`,
    '',
    '# Default extension (primary device)',
    `SIP_EXTENSION=${config.devices[0].extension}`,
    `SIP_AUTH_ID=${config.devices[0].authId}`,
    `SIP_PASSWORD=${config.devices[0].password}`,
    '',
    '# Gemini API Server',
    `GEMINI_API_URL=${geminiApiUrl}`,
    '',
    '# ElevenLabs TTS',
    `ELEVENLABS_API_KEY=${config.api.elevenlabs.apiKey}`,
    `ELEVENLABS_VOICE_ID=${config.devices[0].voiceId}`,
    '',
    '# OpenAI (Whisper STT)',
    `OPENAI_API_KEY=${config.api.openai.apiKey}`,
    '',
    '# Gemini API Key',
    `GEMINI_API_KEY=${config.api.gemini?.apiKey || ''}`,
    `MISSION_CONTROL_GEMINI_KEY=${config.api.gemini?.missionControlKey || ''}`,
    '',
    '# Application Settings',
    `HTTP_PORT=${httpPort}`,
    `WS_PORT=${wsPort}`,
    'AUDIO_DIR=/app/audio',
    `STACK_ID=${stackId}`,
    '',
    '# Outbound Call Settings',
    `DEFAULT_CALLER_ID=${config.outbound?.callerId || ''}`,
    `DIAL_PREFIX=${config.outbound?.dialPrefix || ''}`,
    `MAX_CONVERSATION_TURNS=${config.outbound?.maxTurns || 10}`,
    `OUTBOUND_RING_TIMEOUT=${config.outbound?.ringTimeout || 30}`,
    `TEST_PHONE_NUMBER=${config.outbound?.testPhoneNumber || ''}`,
    '',
    '# FreePBX API (Automation)',
    `FREEPBX_API_URL=${config.pbx?.apiUrl || ''}`,
    `FREEPBX_CLIENT_ID=${config.pbx?.clientId || ''}`,
    `FREEPBX_CLIENT_SECRET=${config.pbx?.clientSecret || ''}`,
    `FREEPBX_TRUNK_NAME=${(config.pbx?.trunkName || 'RedSpot') + (stackId > 1 ? '-' + stackId : '')}`,
    `GEMINI_APP_STACK_IP=${config.pbx?.appStackIp || ''}`,
    '',
    '# n8n Integration',
    `N8N_WEBHOOK_URL=${(config.n8n && config.n8n.webhookUrl) || ''}`,
    `N8N_API_KEY=${(config.n8n && config.n8n.apiKey) || ''}`,
    `N8N_BASE_URL=${(config.n8n && config.n8n.baseUrl) || ''}`,
    ''
  ];

  return lines.join('\n');
}

/**
 * Write Docker configuration files
 * @param {object} config
 * @param {number} stackId - Default 1
 */
export async function writeDockerConfig(config, stackId = 1) {
  const configDir = getConfigDir();
  const suffix = stackId === 1 ? '' : `-${stackId}`;

  const dockerComposePath = path.join(configDir, `docker-compose${suffix}.yml`);
  const envPath = path.join(configDir, `.env${suffix}`);

  const dockerComposeContent = generateDockerCompose(config, stackId);
  const envContent = generateEnvFile(config, stackId);

  await fs.promises.writeFile(dockerComposePath, dockerComposeContent, { mode: 0o644 });
  await fs.promises.writeFile(envPath, envContent, { mode: 0o600 });
}

/**
 * Build Docker containers
 */
/**
 * Build Docker containers
 * @param {number} stackId - Default 1
 */
export async function buildContainers(stackId = 1) {
  const configDir = getConfigDir();
  const suffix = stackId === 1 ? '' : `-${stackId}`;
  const dockerComposePath = path.join(configDir, `docker-compose${suffix}.yml`);

  if (!fs.existsSync(dockerComposePath)) {
    throw new Error(`Docker configuration not found for stack ${stackId}. Run "gemini-phone stack deploy ${stackId}" first.`);
  }

  const compose = getComposeCommand();
  const composeArgs = [...compose.args, '-f', dockerComposePath, 'build'];

  return new Promise((resolve, reject) => {
    const child = spawn(compose.cmd, composeArgs, {
      cwd: configDir,
      stdio: 'pipe',
      env: { ...process.env, DOCKER_BUILDKIT: '0', COMPOSE_DOCKER_CLI_BUILD: '0' }
    });

    let output = '';
    child.stdout.on('data', (data) => { output += data.toString(); });
    child.stderr.on('data', (data) => { output += data.toString(); });

    child.on('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(`Docker build failed (exit ${code}):\n${output}`));
    });
  });
}

/**
 * Start Docker containers
 */
/**
 * Start Docker containers
 * @param {number} stackId - Default 1
 */
export async function startContainers(stackId = 1) {
  const configDir = getConfigDir();
  const suffix = stackId === 1 ? '' : `-${stackId}`;
  const dockerComposePath = path.join(configDir, `docker-compose${suffix}.yml`);

  if (!fs.existsSync(dockerComposePath)) {
    throw new Error(`Docker configuration not found for stack ${stackId}. Run "gemini-phone stack deploy ${stackId}" first.`);
  }

  const compose = getComposeCommand();
  const composeArgs = [...compose.args, '-f', dockerComposePath, 'up', '-d', '--remove-orphans'];

  return new Promise((resolve, reject) => {
    const child = spawn(compose.cmd, composeArgs, {
      cwd: configDir,
      stdio: 'pipe'
    });

    let output = '';
    child.stdout.on('data', (data) => { output += data.toString(); });
    child.stderr.on('data', (data) => { output += data.toString(); });

    child.on('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(`Docker compose failed (exit ${code}): ${output}`));
    });
  });
}

/**
 * Stop Docker containers
 */
/**
 * Stop Docker containers
 * @param {number} stackId - Default 1
 */
export async function stopContainers(stackId = 1) {
  const configDir = getConfigDir();
  const suffix = stackId === 1 ? '' : `-${stackId}`;
  const dockerComposePath = path.join(configDir, `docker-compose${suffix}.yml`);

  if (!fs.existsSync(dockerComposePath)) return;

  const compose = getComposeCommand();
  const composeArgs = [...compose.args, '-f', dockerComposePath, 'down'];

  return new Promise((resolve, reject) => {
    const child = spawn(compose.cmd, composeArgs, {
      cwd: configDir,
      stdio: 'pipe'
    });

    let output = '';
    child.stdout.on('data', (data) => { output += data.toString(); });
    child.stderr.on('data', (data) => { output += data.toString(); });

    child.on('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(`Docker compose down failed (exit ${code}): ${output}`));
    });
  });
}

/**
 * Get status of Docker containers
 */
/**
 * Get status of Docker containers
 * @param {number} stackId - Default 1
 */
export async function getContainerStatus(stackId = 1) {
  const configDir = getConfigDir();
  const suffix = stackId === 1 ? '' : `-${stackId}`;
  const dockerComposePath = path.join(configDir, `docker-compose${suffix}.yml`);

  if (!fs.existsSync(dockerComposePath)) return [];

  const compose = getComposeCommand();
  const composeArgs = [...compose.args, '-f', dockerComposePath, 'ps', '--format', 'json'];

  return new Promise((resolve) => {
    const child = spawn(compose.cmd, composeArgs, {
      cwd: configDir,
      stdio: 'pipe'
    });

    let output = '';
    child.stdout.on('data', (data) => { output += data.toString(); });

    child.on('close', (code) => {
      if (code === 0) {
        try {
          const lines = output.trim().split('\n').filter(l => l);
          const containers = lines.map(line => {
            try {
              const data = JSON.parse(line);
              return {
                name: data.Name || data.Service,
                status: data.State || data.Status
              };
            } catch (e) { return null; }
          }).filter(c => c);
          resolve(containers);
        } catch (error) { resolve([]); }
      } else resolve([]);
    });
  });
}
